# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# ===== Languages =====

Language.create name: "Dari"
Language.create name: "Albanian"
Language.create name: "Arabic"
Language.create name: "Cataln"
Language.create name: "Portuguese"
Language.create name: "English"
Language.create name: "Spanish"
Language.create name: "Armenian"
Language.create name: "German"
Language.create name: "Azerbaijani"
Language.create name: "Bangla"
Language.create name: "Belorussian"
Language.create name: "Dutch"
Language.create name: "Dzongkha"
Language.create name: "Bosnian"
Language.create name: "Malay"
Language.create name: "Bulgarian"
Language.create name: "Kirundi"
Language.create name: "Khmer"
Language.create name: "Chinese"
Language.create name: "Croatian"
Language.create name: "Greek"
Language.create name: "Czech"
Language.create name: "Danish"
Language.create name: "Tetum"
Language.create name: "Afar"
Language.create name: "Estonian"
Language.create name: "Amharic"
Language.create name: "Finnish"
Language.create name: "Georgian"
Language.create name: "Creole"
Language.create name: "Magyar"
Language.create name: "Icelandic"
Language.create name: "Hindi"
Language.create name: "Bahasa"
Language.create name: "Persian"
Language.create name: "Hebrew"
Language.create name: "Italian;"
Language.create name: "Japanese"
Language.create name: "Kazak"
Language.create name: "Korean"
Language.create name: "Kyrgyz"
Language.create name: "Lao"
Language.create name: "Latvian"
Language.create name: "Lithuanian"
Language.create name: "Luxermbourgish"
Language.create name: "Macedonian"
Language.create name: "Malagasy"
Language.create name: "Chichewa"
Language.create name: "Maldivian"
Language.create name: "French"
Language.create name: "Maltese"
Language.create name: "Marshallese"
Language.create name: "Hassaniya"
Language.create name: "Moldovan"
Language.create name: "Mongolian"
Language.create name: "Serbian/Montenegrin"
Language.create name: "Burmese"
Language.create name: "Nauruan"
Language.create name: "Nepali"
Language.create name: "Bokml"
Language.create name: "Urdu"
Language.create name: "Palauan"
Language.create name: "Filipino"
Language.create name: "Polish"
Language.create name: "Arabic;"
Language.create name: "Romanian"
Language.create name: "Russian"
Language.create name: "Kinyarwanda"
Language.create name: "Samoan"
Language.create name: "Italian"
Language.create name: "Serbian"
Language.create name: "Seselwa"
Language.create name: "Mandarin"
Language.create name: "Slovak"
Language.create name: "Slovenian"
Language.create name: "Somali"
Language.create name: "IsiZulu"
Language.create name: "Castilian"
Language.create name: "Sinhala"
Language.create name: "Arabic-Hamitic"
Language.create name: "Swedish"
Language.create name: "Tajik"
Language.create name: "Swahili"
Language.create name: "Thai"
Language.create name: "Tongan"
Language.create name: "Turkish"
Language.create name: "Turkmen"
Language.create name: "Tuvaluan"
Language.create name: "Ukrainian"
Language.create name: "Uzbek"
Language.create name: "Bislama"
Language.create name: "Vietnamese"




Brand.create name: "Alexander McQueen", speciality: "Fashion & Accessories"
Brand.create name: "Alfred Dunhill", speciality: "Fashion & Accessories"
Brand.create name: "APC", speciality: "Fashion & Accessories"
Brand.create name: "Aqua di Parma", speciality: "Other"
Brand.create name: "Armani Collezioni", speciality: "Fashion & Accessories"
Brand.create name: "Emporio Armani", speciality: "Fashion & Accessories"
Brand.create name: "Giorgio Armani", speciality: "Fashion & Accessories"
Brand.create name: "Aston Martin", speciality: "Cars dealer"
Brand.create name: "Audemars Piguet", speciality: "Watchmaker"
Brand.create name: "Audi", speciality: "Cars dealer"
Brand.create name: "Balenciaga", speciality: "Fashion & Accessories"
Brand.create name: "Bally", speciality: "Fashion & Accessories"
Brand.create name: "Balmain", speciality: "Fashion & Accessories"
Brand.create name: "Bang & Olufsen", speciality: "Other"
Brand.create name: "Barbara Bui", speciality: "Fashion & Accessories"
Brand.create name: "Baume et Mercier", speciality: "Watchmaker"
Brand.create name: "Berluti", speciality: "Fashion & Accessories"
Brand.create name: "Dirk Bikkembergs", speciality: "Fashion & Accessories"
Brand.create name: "Blanchet", speciality: "Watchmaker"
Brand.create name: "Blancpain", speciality: "Watchmaker"
Brand.create name: "BMW", speciality: "Cars dealer"
Brand.create name: "Borsalino", speciality: "Fashion & Accessories"
Brand.create name: "Bose", speciality: "Other"
Brand.create name: "Hugo Boss", speciality: "Fashion & Accessories"
Brand.create name: "Bottega Veneta", speciality: "Fashion & Accessories"
Brand.create name: "Boucheron", speciality: "Jewellery"
Brand.create name: "Breguet", speciality: "Watchmaker"
Brand.create name: "Breil", speciality: "Watchmaker"
Brand.create name: "Breitling", speciality: "Watchmaker"
Brand.create name: "Brioni", speciality: "Fashion & Accessories"
Brand.create name: "Brunello Cucinelli", speciality: "Fashion & Accessories"
Brand.create name: "Buccellati", speciality: "Jewellery"
Brand.create name: "Bugatti", speciality: "Cars dealer"
Brand.create name: "Bulgari", speciality: "Jewellery"
Brand.create name: "Burberry", speciality: "Fashion & Accessories"
Brand.create name: "Calvin Klein", speciality: "Fashion & Accessories"
Brand.create name: "Canali", speciality: "Fashion & Accessories"
Brand.create name: "Cartier", speciality: "Jewellery"
Brand.create name: "Roberto Cavalli", speciality: "Fashion & Accessories"
Brand.create name: "Céline", speciality: "Fashion & Accessories"
Brand.create name: "Cerruti", speciality: "Fashion & Accessories"
Brand.create name: "Chanel", speciality: "Fashion & Accessories"
Brand.create name: "Chantal Thomass", speciality: "Fashion & Accessories"
Brand.create name: "Charvet", speciality: "Fashion & Accessories"
Brand.create name: "Chaumet", speciality: "Jewellery"
Brand.create name: "Chloé", speciality: "Fashion & Accessories"
Brand.create name: "Chopard", speciality: "Jewellery"
Brand.create name: "Church’s", speciality: "Fashion & Accessories"
Brand.create name: "Robert Clergerie", speciality: "Fashion & Accessories"
Brand.create name: "Comme des Garçons", speciality: "Fashion & Accessories"
Brand.create name: "Corum", speciality: "Watchmaker"
Brand.create name: "Cutler and Gross", speciality: "Fashion & Accessories"
Brand.create name: "Damiani", speciality: "Jewellery"
Brand.create name: "Davidoff", speciality: "Fashion & Accessories"
Brand.create name: "De Grisogono", speciality: "Jewellery"
Brand.create name: "De Tomaso", speciality: "Cars dealer"
Brand.create name: "Dior", speciality: "Fashion & Accessories"
Brand.create name: "DKNY", speciality: "Fashion & Accessories"
Brand.create name: "Dolce & Gabbana", speciality: "Fashion & Accessories"
Brand.create name: "Adolfo Dominguez", speciality: "Fashion & Accessories"
Brand.create name: "S. T. Dupont", speciality: "Fashion & Accessories"
Brand.create name: "Etro", speciality: "Fashion & Accessories"
Brand.create name: "Façonnable", speciality: "Fashion & Accessories"
Brand.create name: "Fauchon", speciality: "Other"
Brand.create name: "Fendi", speciality: "Fashion & Accessories"
Brand.create name: "Salvatore Ferragamo", speciality: "Fashion & Accessories"
Brand.create name: "Ferrari", speciality: "Cars dealer"
Brand.create name: "Anne Fontaine", speciality: "Fashion & Accessories"
Brand.create name: "Tom Ford", speciality: "Fashion & Accessories"
Brand.create name: "Frédérique Constant", speciality: "Watchmaker"
Brand.create name: "Frey Wille", speciality: "Jewellery"
Brand.create name: "Jean-Paul Gaultier", speciality: "Fashion & Accessories"
Brand.create name: "Givenchy", speciality: "Fashion & Accessories"
Brand.create name: "Goyard", speciality: "Fashion & Accessories"
Brand.create name: "Gucci", speciality: "Fashion & Accessories"
Brand.create name: "Guerlain", speciality: "Other"
Brand.create name: "Harry Winston", speciality: "Jewellery"
Brand.create name: "Hermès", speciality: "Fashion & Accessories"
Brand.create name: "Caroline Herrera", speciality: "Fashion & Accessories"
Brand.create name: "Heschung", speciality: "Fashion & Accessories"
Brand.create name: "Hogan", speciality: "Fashion & Accessories"
Brand.create name: "Vivienne Hu", speciality: "Fashion & Accessories"
Brand.create name: "Hublot", speciality: "Watchmaker"
Brand.create name: "Inès de la Fressange", speciality: "Fashion & Accessories"
Brand.create name: "IWC", speciality: "Watchmaker"
Brand.create name: "Marc Jacobs", speciality: "Fashion & Accessories"
Brand.create name: "Jaguar", speciality: "Cars dealer"
Brand.create name: "Jaeger-Lecoultre", speciality: "Watchmaker"
Brand.create name: "Jimmy Choo", speciality: "Fashion & Accessories"
Brand.create name: "Paule Ka", speciality: "Fashion & Accessories"
Brand.create name: "Stéphane Kélian", speciality: "Fashion & Accessories"
Brand.create name: "Kenzo", speciality: "Fashion & Accessories"
Brand.create name: "Michael Kors", speciality: "Fashion & Accessories"
Brand.create name: "Christian Lacroix", speciality: "Fashion & Accessories"
Brand.create name: "Karl Lagarfeld", speciality: "Fashion & Accessories"
Brand.create name: "La Martina", speciality: "Fashion & Accessories"
Brand.create name: "Lamborghini", speciality: "Cars dealer"
Brand.create name: "Lancel", speciality: "Fashion & Accessories"
Brand.create name: "Helmut Lang", speciality: "Fashion & Accessories"
Brand.create name: "Lanvin", speciality: "Fashion & Accessories"
Brand.create name: "Leonard", speciality: "Fashion & Accessories"
Brand.create name: "Liu Jo", speciality: "Fashion & Accessories"
Brand.create name: "John Lobb", speciality: "Fashion & Accessories"
Brand.create name: "Loewe", speciality: "Fashion & Accessories"
Brand.create name: "Longchamp", speciality: "Fashion & Accessories"
Brand.create name: "Longines", speciality: "Watchmaker"
Brand.create name: "Loro Piana", speciality: "Fashion & Accessories"
Brand.create name: "Christian Louboutin", speciality: "Fashion & Accessories"
Brand.create name: "Maison Margiela", speciality: "Fashion & Accessories"
Brand.create name: "Mac Laren", speciality: "Cars dealer"
Brand.create name: "Max Mara", speciality: "Fashion & Accessories"
Brand.create name: "Maserati", speciality: "Cars dealer"
Brand.create name: "Maybach", speciality: "Cars dealer"
Brand.create name: "Mercedes-benz", speciality: "Cars dealer"
Brand.create name: "Messika", speciality: "Jewellery"
Brand.create name: "Richard Mille", speciality: "Watchmaker"
Brand.create name: "Missoni", speciality: "Fashion & Accessories"
Brand.create name: "Miu Miu", speciality: "Fashion & Accessories"
Brand.create name: "Issey Miyake", speciality: "Fashion & Accessories"
Brand.create name: "Moncler", speciality: "Fashion & Accessories"
Brand.create name: "Montblanc", speciality: "Fashion & Accessories"
Brand.create name: "Moschino", speciality: "Fashion & Accessories"
Brand.create name: "Mulberry", speciality: "Fashion & Accessories"
Brand.create name: "Omega", speciality: "Watchmaker"
Brand.create name: "Cesare Paciotti", speciality: "Fashion & Accessories"
Brand.create name: "Petrossian", speciality: "Other"
Brand.create name: "Panerai", speciality: "Watchmaker"
Brand.create name: "Patrizia Pepe", speciality: "Fashion & Accessories"
Brand.create name: "Patek Philippe", speciality: "Watchmaker"
Brand.create name: "Paul & Joe", speciality: "Fashion & Accessories"
Brand.create name: "Piaget", speciality: "Watchmaker"
Brand.create name: "Poiray", speciality: "Jewellery"
Brand.create name: "Porsche", speciality: "Cars dealer"
Brand.create name: "Pomellato", speciality: "Jewellery"
Brand.create name: "Prada", speciality: "Fashion & Accessories"
Brand.create name: "Emilio Pucci", speciality: "Fashion & Accessories"
Brand.create name: "Rado", speciality: "Watchmaker"
Brand.create name: "Ralph Lauren", speciality: "Fashion & Accessories"
Brand.create name: "Nina Ricci", speciality: "Fashion & Accessories"
Brand.create name: "Rolex", speciality: "Watchmaker"
Brand.create name: "Rolls-Royce", speciality: "Cars dealer"
Brand.create name: "Fratelli Rossetti", speciality: "Fashion & Accessories"
Brand.create name: "Jil Sander", speciality: "Fashion & Accessories"
Brand.create name: "Sergio Rossi", speciality: "Fashion & Accessories"
Brand.create name: "Sonia Rykiel", speciality: "Fashion & Accessories"
Brand.create name: "Saint-Laurent Paris", speciality: "Fashion & Accessories"
Brand.create name: "Francesco Smalto", speciality: "Fashion & Accessories"
Brand.create name: "Paul Smith", speciality: "Fashion & Accessories"
Brand.create name: "Stella McCartney", speciality: "Fashion & Accessories"
Brand.create name: "Swarovski", speciality: "Jewellery"
Brand.create name: "TAG Heuer", speciality: "Watchmaker"
Brand.create name: "Tiffany & Co.", speciality: "Jewellery"
Brand.create name: "Tissot", speciality: "Watchmaker"
Brand.create name: "Tod’s", speciality: "Fashion & Accessories"
Brand.create name: "Tory Burch", speciality: "Fashion & Accessories"
Brand.create name: "Trussardi", speciality: "Fashion & Accessories"
Brand.create name: "Tumi", speciality: "Fashion & Accessories"
Brand.create name: "Vacheron Constantin", speciality: "Watchmaker"
Brand.create name: "Valentino", speciality: "Fashion & Accessories"
Brand.create name: "Van Cleef & Arpels", speciality: "Jewellery"
Brand.create name: "Dries Van Noten", speciality: "Fashion & Accessories"
Brand.create name: "Versace", speciality: "Fashion & Accessories"
Brand.create name: "Vertu", speciality: "Other"
Brand.create name: "Victor & Rolf", speciality: "Fashion & Accessories"
Brand.create name: "Roger Vivier", speciality: "Fashion & Accessories"
Brand.create name: "Louis Vuitton", speciality: "Fashion & Accessories"
Brand.create name: "Vera Wang", speciality: "Fashion & Accessories"
Brand.create name: "Stuart Weitzman", speciality: "Fashion & Accessories"
Brand.create name: "JM Weston", speciality: "Fashion & Accessories"
Brand.create name: "Vivienne Westwood", speciality: "Fashion & Accessories"
Brand.create name: "Wiesmann", speciality: "Cars dealer"
Brand.create name: "Wooyoungmi", speciality: "Fashion & Accessories"
Brand.create name: "Y3", speciality: "Fashion & Accessories"
Brand.create name: "Yohji Yamamoto", speciality: "Fashion & Accessories"
Brand.create name: "Giuseppe Zanotti", speciality: "Fashion & Accessories"
Brand.create name: "Ermenegildo Zegna", speciality: "Fashion & Accessories"
Brand.create name: "Zenith", speciality: "Watchmaker"