# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# ===== Languages =====

Language.create name: "Dari"
Language.create name: "Albanian"
Language.create name: "Arabic"
Language.create name: "Cataln"
Language.create name: "Portuguese"
Language.create name: "English"
Language.create name: "Spanish"
Language.create name: "Armenian"
Language.create name: "German"
Language.create name: "Azerbaijani"
Language.create name: "Bangla"
Language.create name: "Belorussian"
Language.create name: "Dutch"
Language.create name: "Dzongkha"
Language.create name: "Bosnian"
Language.create name: "Malay"
Language.create name: "Bulgarian"
Language.create name: "Kirundi"
Language.create name: "Khmer"
Language.create name: "Chinese"
Language.create name: "Croatian"
Language.create name: "Greek"
Language.create name: "Czech"
Language.create name: "Danish"
Language.create name: "Tetum"
Language.create name: "Afar"
Language.create name: "Estonian"
Language.create name: "Amharic"
Language.create name: "Finnish"
Language.create name: "Georgian"
Language.create name: "Creole"
Language.create name: "Magyar"
Language.create name: "Icelandic"
Language.create name: "Hindi"
Language.create name: "Bahasa"
Language.create name: "Persian"
Language.create name: "Hebrew"
Language.create name: "Italian;"
Language.create name: "Japanese"
Language.create name: "Kazak"
Language.create name: "Korean"
Language.create name: "Kyrgyz"
Language.create name: "Lao"
Language.create name: "Latvian"
Language.create name: "Lithuanian"
Language.create name: "Luxermbourgish"
Language.create name: "Macedonian"
Language.create name: "Malagasy"
Language.create name: "Chichewa"
Language.create name: "Maldivian"
Language.create name: "French"
Language.create name: "Maltese"
Language.create name: "Marshallese"
Language.create name: "Hassaniya"
Language.create name: "Moldovan"
Language.create name: "Mongolian"
Language.create name: "Serbian/Montenegrin"
Language.create name: "Burmese"
Language.create name: "Nauruan"
Language.create name: "Nepali"
Language.create name: "Bokml"
Language.create name: "Urdu"
Language.create name: "Palauan"
Language.create name: "Filipino"
Language.create name: "Polish"
Language.create name: "Arabic;"
Language.create name: "Romanian"
Language.create name: "Russian"
Language.create name: "Kinyarwanda"
Language.create name: "Samoan"
Language.create name: "Italian"
Language.create name: "Serbian"
Language.create name: "Seselwa"
Language.create name: "Mandarin"
Language.create name: "Slovak"
Language.create name: "Slovenian"
Language.create name: "Somali"
Language.create name: "IsiZulu"
Language.create name: "Castilian"
Language.create name: "Sinhala"
Language.create name: "Arabic-Hamitic"
Language.create name: "Swedish"
Language.create name: "Tajik"
Language.create name: "Swahili"
Language.create name: "Thai"
Language.create name: "Tongan"
Language.create name: "Turkish"
Language.create name: "Turkmen"
Language.create name: "Tuvaluan"
Language.create name: "Ukrainian"
Language.create name: "Uzbek"
Language.create name: "Bislama"
Language.create name: "Vietnamese"
